// <auto-generated />
namespace CriacaoTurmas.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class modificacao4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modificacao4));
        
        string IMigrationMetadata.Id
        {
            get { return "201809041356043_modificacao4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
